name: Sugoroku_craft
version: ${project.version}
main: yoneyone.yone.yo.sugoroku_craft.Sugoroku_craft
commands:
  test:
    description: テスト用コマンド
  masu:
    description: マスを作るコマンド
  sgo:
    description: サイコロ用コマンド
  mgo:
    description: 進む用コマンド